### ISSUE TITLE
Where is the function config() defined?

### ISSUE THREAD

**Issue by leetschau** [sczyh30/vertx-blueprint-todo-backend#3]
Where is the definition of `config()` in [L46](https://github.com/sczyh30/vertx-blueprint-todo-backend/blob/master/src/main/java/io/vertx/blueprint/todolist/verticles/TodoVerticle.java#L46) of the file src/main/java/io/vertx/blueprint/todolist/verticles/TodoVerticle.java?
Thanks.

```
final String serviceType = config().getString("service.type", "redis");
```

**Comment by sczyh30** [comment]
It's in [`AbstractVerticle` class](https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/AbstractVerticle.java#L89).

**Comment by leetschau** [comment]
OK, thanks.
