### ISSUE TITLE
Codegen not working

### ISSUE THREAD

**Issue by gaurav4j-xx** [sczyh30/vertx-blueprint-todo-backend#5]
Hi

I was following your tutorial and was actually creating the todo backend service on my local machine. Looks like the code generation doesn't works for me. 

I even downloaded the code from your repo and build that too but TodoConverter.java doesn't gets generated post compilation. (I purposely deleted the generated folder before compile/build the project)

**Comment by sczyh30** [comment]
Hi, the code generation should be executed during the `annotationProcessing` task defined in [`build.gradle`](https://github.com/sczyh30/vertx-blueprint-todo-backend/blob/master/build.gradle#L26) (and the `build` task depends on it).  You may try to execute `gradle annotationProcessing` and see if there are any error hints. Be sure your Gradle version >= 2.12 (or use gradlew directly).

**Comment by gaurav4j-xx** [comment]
Thanks, mate. Working now. 👍
